# - name: Docker install and configuration
#   hosts: _development
#   become: true
#   roles: 
#     - geerlingguy.docker

# - name: Postgre Database configuration
#   hosts: _ansible_postgresql_o
#   become: true
#   roles:
#     - postgre

- name: Nodejs server configuration
  hosts: _ansible_nodejs_o
  become: true
  roles:
    - nodejs

# - name: React UI Server configuration
#   hosts: _ansible_react_o
#   become: true
#   roles:
#     - react